#pragma once

// keywords
#define	ฝᓎಳϑෂฝҀ	alignas
#define	ฝᓎಳϑෂɚᓗ	alignof
#define	ฝෂට	and
#define	ฝෂට_ᕓж	and_eq
#define	ฝҀᖘ	asm
#define	ฝᾦᎲɚ	auto
#define	ळಳᎲฝෂට	bitand
#define	ळಳᎲɚ٧	bitor
#define	ळɚɚᓎ	bool
#define	ळ٧ᕓฝโ	break
#define	ತฝҀᕓ	case
#define	ತฝᎲತɷ	catch
#define	ತɷฝ٧	char
#define	ತɷฝ٧16_Ꮂ	char16_t
#define	ತɷฝ٧32_Ꮂ	char32_t
#define	ತᓎฝҀҀ	class
#define	ತɚᖘඹᓎ	compl
#define	ತɚෂತᕓඹᎲ	concept
#define	ತɚෂҀᎲ	const
#define	ತɚෂҀᎲᕓษඹ٧	constexpr
#define	ತɚෂҀᎲ_ತฝҀᎲ	const_cast
#define	ತɚෂᎲಳෂᾦᕓ	continue
#define	ටᕓತᓎᎲหඹᕓ	decltype
#define	ටᕓᓗฝᾦᓎᎲ	default
#define	ටᕓᓎᕓᎲᕓ	delete
#define	ටɚ	do
#define	ටɚᾦळᓎᕓ	double
#define	ටหෂฝᖘಳತ_ತฝҀᎲ	dynamic_cast
#define	ᕓᓎҀᕓ	else
#define	ᕓෂᾦᖘ	enum
#define	ᕓษඹᓎಳತಳᎲ	explicit
#define	ᕓษඹɚ٧Ꮂ	export
#define	ᕓษᎲᕓ٧ෂ	extern
#define	ᓗฝᓎҀᕓ	false
#define	ᓗᓎɚฝᎲ	float
#define	ᓗɚ٧	for
#define	ᓗ٧ಳᕓෂට	friend
#define	ϑɚᎲɚ	goto
#define	ಳᓗ	if
#define	ಳෂᓎಳෂᕓ	inline
#define	ಳෂᎲ	int
#define	ᓎɚෂϑ	long
#define	ᖘᾦᎲฝळᓎᕓ	mutable
#define	ෂฝᖘᕓҀඹฝತᕓ	namespace
#define	ෂᕓٮ		new
#define	ෂɚᕓษತᕓඹᎲ	noexcept
#define	ෂɚᎲ	not
#define	ෂɚᎲ_ᕓж	not_eq
#define	ෂᾦᓎᓎඹᎲ٧	nullptr
#define	ɚඹᕓ٧ฝᎲɚ٧	operator
#define	ɚ٧	or
#define	ɚ٧_ᕓж	or_eq
#define	ඹ٧ಳଳฝᎲᕓ	private
#define	ඹ٧ɚᎲᕓತᎲᕓට	protected
#define	ඹᾦळᓎಳತ	public
#define	٧ᕓϑಳҀᎲᕓ٧	register
#define	٧ᕓಳෂᎲᕓ٧ඹ٧ᕓᎲ_ತฝҀᎲ	reinterpret_cast
#define	٧ᕓжᾦಳ٧ᕓҀ	requires
#define	٧ᕓᎲᾦ٧ෂ	return
#define	Ҁɷɚ٧Ꮂ	short
#define	Ҁಳϑෂᕓට	signed
#define	Ҁಳൺᕓɚᓗ	sizeof
#define	ҀᎲฝᎲಳತ	static
#define	ҀᎲฝᎲಳತ_ฝҀҀᕓ٧Ꮂ	static_assert
#define	ҀᎲฝᎲಳತ_ತฝҀᎲ	static_cast
#define	ҀᎲ٧ᾦತᎲ	struct
#define	ҀٮಳᎲತɷ	switch
#define	ᎲᕓᖘඹᓎฝᎲᕓ	template
#define	ᎲɷಳҀ	this
#define	Ꮂɷ٧ᕓฝට_ᓎɚತฝᓎ	thread_local
#define	Ꮂɷ٧ɚٮ	throw
#define	Ꮂ٧ᾦᕓ	true
#define	Ꮂ٧ห	try
#define	Ꮂหඹᕓටᕓᓗ	typedef
#define	Ꮂหඹᕓಳට	typeid
#define	Ꮂหඹᕓෂฝᖘᕓ	typename
#define	ᾦෂಳɚෂ	union
#define	ᾦෂҀಳϑෂᕓට	unsigned
#define	ᾦҀಳෂϑ	using
#define	ଳಳ٧Ꮂᾦฝᓎ	virtual
#define	ଳɚಳට	void
#define	ଳɚᓎฝᎲಳᓎᕓ	volatile
#define	ٮತɷฝ٧_Ꮂ	wchar_t
#define	ٮɷಳᓎᕓ	while
#define	ษɚ٧	xor
#define	ษɚ٧_ᕓж	xor_eq

// stdio
#define	Ҁಳൺᕓ_Ꮂ	size_t
#define	Ṫᖺℳڷ	FILE
#define	ᓗඹɚҀ_Ꮂ	fpos_t
#define	ƳĞℳℳ	NULL
#define	_ᖺȬṪҜṪ	_IOFBF
#define	_ᖺȬℳҜṪ	_IOLBF
#define	_ᖺȬƳҜṪ	_IONBF
#define	ҜĞṪತᖺõ	BUFSIZ
#define	ڷȬṪ	EOF
#define	ṪȬᙜڷƳ_ȫ焚ண	FOPEN_MAX
#define	ṪᖺℳڷƳ焚ȫڷ_ȫ焚ண	FILENAME_MAX
#define	ℳ_Ꮂᖘඹෂฝᖘ	L_tmpnam
#define	ತڷڷฐ_ᗑĞҁ	SEEK_CUR
#define	ತڷڷฐ_ڷƳꊱ	SEEK_END
#define	ತڷڷฐ_ತڷᑓ	SEEK_SET
#define	ᑓȫᙜ_ȫ焚ண	TMP_MAX
#define	ҀᎲටᕓ٧٧	stderr
#define	ҀᎲටಳෂ	stdin
#define	ҀᎲටɚᾦᎲ	stdout
#define	ᓗತᓎɚҀᕓ	fclose
#define	ತᓎᕓฝ٧ᕓ٧٧	clearerr
#define	ᓗᕓɚᓗ	feof
#define	ᓗᕓ٧٧ɚ٧	ferror
#define	ᓗᓗᓎᾦҀɷ	fflush
#define	ᓗϑᕓᎲඹɚҀ	fgetpos
#define	ᓗɚඹᕓෂ	fopen
#define	ᓗ٧ᕓฝට	fread
#define	ᓗ٧ᕓɚඹᕓෂ	freopen
#define	ᓗҀᕓᕓโ	fseek
#define	ᓗҀᕓᎲඹɚҀ	fsetpos
#define	ᓗᎲᕓᓎᓎ	ftell
#define	ᓗٮ٧ಳᎲᕓ	fwrite
#define	٧ᕓᖘɚଳᕓ	remove
#define	٧ᕓෂฝᖘᕓ	rename
#define	٧ᕓٮಳෂට	rewind
#define	ҀᕓᎲळᾦᓗ	setbuf
#define	ҀᕓᎲଳळᾦᓗ	setvbuf
#define	Ꮂᖘඹᓗಳᓎᕓ	tmpfile
#define	Ꮂᖘඹෂฝᖘ	tmpnam
#define	ᓗඹ٧ಳෂᎲᓗ	fprintf
#define	ඹ٧ಳෂᎲᓗ	printf
#define	Ҁඹ٧ಳෂᎲᓗ	sprintf
#define	ଳᓗඹ٧ಳෂᎲᓗ	vfprintf
#define	ଳඹ٧ಳෂᎲᓗ	vprintf
#define	ଳҀඹ٧ಳෂᎲᓗ	vsprintf
#define	ᓗҀತฝෂᓗ	fscanf
#define	Ҁತฝෂᓗ	scanf
#define	ҀҀತฝෂᓗ	sscanf
#define	ᓗϑᕓᎲತ	fgetc
#define	ᓗϑᕓᎲҀ	fgets
#define	ᓗඹᾦᎲತ	fputc
#define	ᓗඹᾦᎲҀ	fputs
#define	ϑᕓᎲತ	getc
#define	ϑᕓᎲತɷฝ٧	getchar
#define	ϑᕓᎲҀ	gets
#define	ඹᾦᎲತ	putc
#define	ඹᾦᎲತɷฝ٧	putchar
#define	ඹᾦᎲҀ	puts
#define	ᾦෂϑᕓᎲತ	ungetc
#define	ඹᕓ٧٧ɚ٧	perror

// stdlib
#define	ටಳଳ_Ꮂ	div_t
#define	ᓎටಳଳ_Ꮂ	ldiv_t
#define	ڷணᖺᑓ_Ṫ焚ᖺℳĞҁڷ	EXIT_FAILURE
#define	ڷணᖺᑓ_ತĞᗑᗑڷತತ	EXIT_SUCCESS
#define	ҁ焚Ƴꊱ_ȫ焚ண	RAND_MAX
#define	ȫҜ_ᗑĞҁ_ȫ焚ண	MB_CUR_MAX
#define	ȫҜ_ℳڷƳ_ȫ焚ண	MB_LEN_MAX
#define	ฝᎲɚᓗ	atof
#define	ฝᎲɚಳ	atoi
#define	ฝᎲɚᓎ	atol
#define	ҀᎲ٧Ꮂɚට	strtod
#define	ҀᎲ٧Ꮂɚᓎ	strtol
#define	ҀᎲ٧Ꮂɚᾦᓎ	strtoul
#define	ತฝᓎᓎɚತ	calloc
#define	ᓗ٧ᕓᕓ	free
#define	ᖘฝᓎᓎɚತ	malloc
#define	٧ᕓฝᓎᓎɚತ	realloc
#define	ฝळɚ٧Ꮂ	abort
#define	ฝᎲᕓษಳᎲ	atexit
#define	ᕓษಳᎲ	exit
#define	ϑᕓᎲᕓෂଳ	getenv
#define	ҀหҀᎲᕓᖘ	system
#define	ळҀᕓฝ٧ತɷ	bsearch
#define	жҀɚ٧Ꮂ	qsort
#define	ฝळҀ	abs
#define	ටಳଳ	div
#define	ᓎฝळҀ	labs
#define	ᓎටಳଳ	ldiv
#define	٧ฝෂට	rand
#define	Ҁ٧ฝෂට	srand
#define	ᖘळᓎᕓෂ	mblen
#define	ᖘळҀᎲɚٮತҀ	mbstowcs
#define	ᖘळᎲɚٮತ	mbtowc
#define	ٮತҀᎲɚᖘळҀ	wcstombs
#define	ٮತᎲɚᖘळ	wctomb

// string.h
#define	ᖘᕓᖘತඹห	memcpy
#define	ᖘᕓᖘᖘɚଳᕓ	memmove
#define	ҀᎲ٧ತඹห	strcpy
#define	ҀᎲ٧ෂತඹห	strncpy
#define	ҀᎲ٧ತฝᎲ	strcat
#define	ҀᎲ٧ෂತฝᎲ	strncat
#define	ᖘᕓᖘತᖘඹ	memcmp
#define	ҀᎲ٧ತᖘඹ	strcmp
#define	ҀᎲ٧ತɚᓎᓎ	strcoll
#define	ҀᎲ٧ෂತᖘඹ	strncmp
#define	ҀᎲ٧ษᓗ٧ᖘ	strxfrm
#define	ᖘᕓᖘತɷ٧	memchr
#define	ҀᎲ٧ತɷ٧	strchr
#define	ҀᎲ٧ತҀඹෂ	strcspn
#define	ҀᎲ٧ඹळ٧โ	strpbrk
#define	ҀᎲ٧٧ತɷ٧	strrchr
#define	ҀᎲ٧Ҁඹෂ	strspn
#define	ҀᎲ٧ҀᎲ٧	strstr
#define	ҀᎲ٧Ꮂɚโ	strtok
#define	ᖘᕓᖘҀᕓᎲ	memset
#define	ҀᎲ٧ᕓ٧٧ɚ٧	strerror
#define	ҀᎲ٧ᓎᕓෂ	strlen

// iostream
#define	ತಳෂ	cin
#define	ತɚᾦᎲ	cout
#define	ತᕓ٧٧	cerr
#define	ತᓎɚϑ	clog
#define	ٮತಳෂ	wcin
#define	ٮತɚᾦᎲ	wcout
#define	ٮತᕓ٧٧	wcerr
#define	ٮತᓎɚϑ	wclog
